/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DarkFrontierRouteImport } from './routes/dark-frontier'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes/index'
import { Route as RoutesRequestRouteImport } from './routes/routes/request'
import { Route as RoutesSlugRouteImport } from './routes/routes/$slug'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences/$slug'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkFrontierRoute = DarkFrontierRouteImport.update({
  id: '/dark-frontier',
  path: '/dark-frontier',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRequestRoute = RoutesRequestRouteImport.update({
  id: '/routes/request',
  path: '/routes/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesSlugRoute = RoutesSlugRouteImport.update({
  id: '/routes/$slug',
  path: '/routes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dark-frontier': typeof DarkFrontierRoute
  '/discover': typeof DiscoverRoute
  '/guide': typeof GuideRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/routes/request': typeof RoutesRequestRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dark-frontier': typeof DarkFrontierRoute
  '/discover': typeof DiscoverRoute
  '/guide': typeof GuideRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/routes/request': typeof RoutesRequestRoute
  '/routes': typeof RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dark-frontier': typeof DarkFrontierRoute
  '/discover': typeof DiscoverRoute
  '/guide': typeof GuideRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/routes/$slug': typeof RoutesSlugRoute
  '/routes/request': typeof RoutesRequestRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/dark-frontier'
    | '/discover'
    | '/guide'
    | '/partner'
    | '/profile'
    | '/experiences/$slug'
    | '/routes/$slug'
    | '/routes/request'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/dark-frontier'
    | '/discover'
    | '/guide'
    | '/partner'
    | '/profile'
    | '/experiences/$slug'
    | '/routes/$slug'
    | '/routes/request'
    | '/routes'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/dark-frontier'
    | '/discover'
    | '/guide'
    | '/partner'
    | '/profile'
    | '/experiences/$slug'
    | '/routes/$slug'
    | '/routes/request'
    | '/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  DarkFrontierRoute: typeof DarkFrontierRoute
  DiscoverRoute: typeof DiscoverRoute
  GuideRoute: typeof GuideRoute
  PartnerRoute: typeof PartnerRoute
  ProfileRoute: typeof ProfileRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
  RoutesSlugRoute: typeof RoutesSlugRoute
  RoutesRequestRoute: typeof RoutesRequestRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-frontier': {
      id: '/dark-frontier'
      path: '/dark-frontier'
      fullPath: '/dark-frontier'
      preLoaderRoute: typeof DarkFrontierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/request': {
      id: '/routes/request'
      path: '/routes/request'
      fullPath: '/routes/request'
      preLoaderRoute: typeof RoutesRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$slug': {
      id: '/routes/$slug'
      path: '/routes/$slug'
      fullPath: '/routes/$slug'
      preLoaderRoute: typeof RoutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  DarkFrontierRoute: DarkFrontierRoute,
  DiscoverRoute: DiscoverRoute,
  GuideRoute: GuideRoute,
  PartnerRoute: PartnerRoute,
  ProfileRoute: ProfileRoute,
  ExperiencesSlugRoute: ExperiencesSlugRoute,
  RoutesSlugRoute: RoutesSlugRoute,
  RoutesRequestRoute: RoutesRequestRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
